services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres-db
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRESQL_DATABASE: ${DB_NAME}
      POSTGRESQL_USERNAME: ${DB_USER}
      POSTGRESQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/bitnami/postgresql
    networks:
      - postgres-network
      
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:

networks:
  postgres-network: