services:
  cassandra:
    image: cassandra:5.0
    container_name: cassandra-db
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: video-streaming-cluster
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - cassandra-network

volumes:
  cassandra_data:

networks:
  cassandra-network: 